### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by beldmit** [provider-corner/vigenere#1]
1. Why do you use the malloc/free functions instead of the OPENSSL_malloc/free?
2. Is the old way of generating the error files (using the `mkerr.pl` script) still relevant?

**Comment by levitte** [comment]
1. Because I can. There's literally *nothing* that says I must use the OpenSSL specific functions.
2. `mkerr.pl` has never been a good tool outside of OpenSSL, there are simply too many dependencies on internals. What we have done is to allow providers to give their own table of reason code <-> reason string tuples, which they can easily generate in whatever fashion they want. In this case, there is so little that I decided to do it entirely manually.

**Comment by levitte** [comment]
Re 2, the error functions do feel a bit clumsy. I addressed that [here](https://github.com/openssl/openssl/issues/10302)

**Comment by levitte** [comment]
Oh boy, this isn't closed yet?

Anyway, you might be interested in the small library for providers that I've started, see https://github.com/provider-corner/libprov
